patch_size: 16
dim: 256
layers: 6

block_config:
  - type: model.SelfAttention
    length_dim: l
    params:
      head_dim: 64
      use_qk_norm: true
  - type: model.SelfAttention
    length_dim: vl
    params:
      head_dim: 64
      use_qk_norm: true
      block_causal: true
  - type: model.MLP
    length_dim: vl
    params:
      inter_multi: 4
